export const SET_PRODUCTS = `SET_PRODUCTS`;
export const SET_PRODUCT = `SET_PRODUCT`;
export const SET_PRODUCTS_ERROR = `SET_PRODUCTS_ERROR`;
export const REMOVE_PRODUCT = `REMOVE_PRODUCT`;

export const SET_BASKET_ERROR = `SET_BASKET_ERROR`;
export const SET_BASKET = `SET_BASKET`;
export const CLEAR_BASKET = `CLEAR_BASKET`;
